/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Color;

/**
 *
 * @author AG
 */
public class JFraCuenta extends javax.swing.JFrame {

    /**
     * Creates new form JFraCuenta
     */
    public JFraCuenta() {
        initComponents();
        jTFIdCuenta.setBackground(new Color(0,0,0,0));
        jTFFecha.setBackground(new Color(0,0,0,0));
        jTFSaldo.setBackground(new Color(0,0,0,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTFIdCuenta = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jTFFecha = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jCbCliente = new javax.swing.JComboBox<>();
        jCbCuenta = new javax.swing.JComboBox<>();
        jTFSaldo = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jBtCancelar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();
        jBtnNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 47, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 550, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 700, 210));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFIdCuenta.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFIdCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jTFIdCuenta.setText("Id:");
        jTFIdCuenta.setBorder(null);
        jPanel2.add(jTFIdCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 30, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 190, 10));

        jTFFecha.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFFecha.setForeground(new java.awt.Color(255, 255, 255));
        jTFFecha.setText("Ingresar Fecha");
        jTFFecha.setBorder(null);
        jTFFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFFechaMousePressed(evt);
            }
        });
        jPanel2.add(jTFFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 180, -1));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 190, 10));

        jCbCliente.setBackground(new java.awt.Color(255, 255, 255));
        jCbCliente.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jCbCliente.setForeground(new java.awt.Color(255, 255, 255));
        jCbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jCbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 190, -1));

        jCbCuenta.setBackground(new java.awt.Color(255, 255, 255));
        jCbCuenta.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jCbCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jCbCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jCbCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 190, -1));

        jTFSaldo.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFSaldo.setForeground(new java.awt.Color(255, 255, 255));
        jTFSaldo.setText("Ingresar Saldo");
        jTFSaldo.setBorder(null);
        jTFSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFSaldoMouseClicked(evt);
            }
        });
        jPanel2.add(jTFSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 180, -1));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 190, 10));

        jBtCancelar.setBackground(new java.awt.Color(36, 47, 70));
        jBtCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBtCancelar.setText("Cancelar");
        jPanel2.add(jBtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 140, 40));

        jBtnEliminar.setBackground(new java.awt.Color(36, 47, 70));
        jBtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEliminar.setText("Eliminar");
        jPanel2.add(jBtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 140, 40));

        jBtnEditar.setBackground(new java.awt.Color(36, 47, 70));
        jBtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEditar.setText("Editar");
        jPanel2.add(jBtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 140, 40));

        jBtnGuardar.setBackground(new java.awt.Color(36, 47, 70));
        jBtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGuardar.setText("Guardar");
        jPanel2.add(jBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 140, 40));

        jBtnNuevo.setBackground(new java.awt.Color(36, 47, 70));
        jBtnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNuevo.setText("Nuevo");
        jPanel2.add(jBtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 140, 40));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        jLabel2.setText("Area Cuenta");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFFechaMousePressed
        // TODO add your handling code here:
        jTFFecha.setText("");
    }//GEN-LAST:event_jTFFechaMousePressed

    private void jTFSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFSaldoMouseClicked
        // TODO add your handling code here:
        jTFSaldo.setText("");
    }//GEN-LAST:event_jTFSaldoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFraCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFraCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFraCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFraCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFraCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JComboBox<String> jCbCliente;
    private javax.swing.JComboBox<String> jCbCuenta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFIdCuenta;
    private javax.swing.JTextField jTFSaldo;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
