/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Color;

/**
 *
 * @author octaviolopez
 */
public class JFraClientes extends javax.swing.JFrame {

    /**
     * Creates new form JFraClientes
     */
    public JFraClientes() {
        initComponents();
        jTFApellido.setBackground(new Color(0,0,0,0));
        jTFNombre.setBackground(new Color(0,0,0,0));
        jTFId.setBackground(new Color(0,0,0,0));
        jTFTelefono.setBackground(new Color(0,0,0,0));
        
        
        
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        scroll.setBorder(null);
        
        
        
        
        jTxADireccion.setBackground(new Color(0,0,0,0));
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jTFApellido = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jTFNombre = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jTFId = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jTFTelefono = new javax.swing.JTextField();
        jCbSexo = new javax.swing.JComboBox<>();
        jCbSexo1 = new javax.swing.JComboBox<>();
        scroll = new javax.swing.JScrollPane();
        jTxADireccion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jBtnNuevo = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 190, 10));

        jTFApellido.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFApellido.setForeground(new java.awt.Color(255, 255, 255));
        jTFApellido.setText("Ingresar Apellido");
        jTFApellido.setBorder(null);
        jTFApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFApellidoMousePressed(evt);
            }
        });
        getContentPane().add(jTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 180, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 190, 10));

        jTFNombre.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTFNombre.setText("Ingresar Nombre");
        jTFNombre.setBorder(null);
        jTFNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFNombreMousePressed(evt);
            }
        });
        getContentPane().add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, -1));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 190, 10));

        jTFId.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFId.setForeground(new java.awt.Color(255, 255, 255));
        jTFId.setText("Id:");
        jTFId.setBorder(null);
        jTFId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFIdMousePressed(evt);
            }
        });
        getContentPane().add(jTFId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 30, -1));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 190, 10));

        jTFTelefono.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jTFTelefono.setText("Ingresar Telefono");
        jTFTelefono.setBorder(null);
        jTFTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFTelefonoMousePressed(evt);
            }
        });
        getContentPane().add(jTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 180, -1));

        jCbSexo.setBackground(new java.awt.Color(255, 255, 255));
        jCbSexo.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jCbSexo.setForeground(new java.awt.Color(255, 255, 255));
        jCbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jCbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 190, -1));

        jCbSexo1.setBackground(new java.awt.Color(255, 255, 255));
        jCbSexo1.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jCbSexo1.setForeground(new java.awt.Color(255, 255, 255));
        jCbSexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jCbSexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, -1));

        jTxADireccion.setColumns(20);
        jTxADireccion.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTxADireccion.setForeground(new java.awt.Color(255, 255, 255));
        jTxADireccion.setRows(5);
        jTxADireccion.setText("Direccion");
        jTxADireccion.setToolTipText("");
        jTxADireccion.setOpaque(false);
        jTxADireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTxADireccionMousePressed(evt);
            }
        });
        scroll.setViewportView(jTxADireccion);

        getContentPane().add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 320, 100));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        jLabel2.setText("Area Clientes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jBtnNuevo.setBackground(new java.awt.Color(36, 47, 70));
        jBtnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNuevo.setText("Nuevo");
        getContentPane().add(jBtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 140, 40));

        jBtnGuardar.setBackground(new java.awt.Color(36, 47, 70));
        jBtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGuardar.setText("Guardar");
        getContentPane().add(jBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 140, 40));

        jBtnEliminar.setBackground(new java.awt.Color(36, 47, 70));
        jBtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEliminar.setText("Eliminar");
        getContentPane().add(jBtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 140, 40));

        jBtnEditar.setBackground(new java.awt.Color(36, 47, 70));
        jBtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEditar.setText("Editar");
        getContentPane().add(jBtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 140, 40));

        jBtCancelar.setBackground(new java.awt.Color(36, 47, 70));
        jBtCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBtCancelar.setText("Cancelar");
        getContentPane().add(jBtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clientes.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        jPanel1.setBackground(new java.awt.Color(36, 47, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 700, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFApellidoMousePressed
        // TODO add your handling code here:
        jTFApellido.setText("");
    }//GEN-LAST:event_jTFApellidoMousePressed

    private void jTFNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNombreMousePressed
        // TODO add your handling code here:
        jTFNombre.setText("");
    }//GEN-LAST:event_jTFNombreMousePressed

    private void jTFIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFIdMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIdMousePressed

    private void jTFTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFTelefonoMousePressed
        // TODO add your handling code here:
        jTFTelefono.setText("");
    }//GEN-LAST:event_jTFTelefonoMousePressed

    private void jTxADireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxADireccionMousePressed
        // TODO add your handling code here:
        jTxADireccion.setText("");
    }//GEN-LAST:event_jTxADireccionMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFraClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFraClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFraClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFraClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFraClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JComboBox<String> jCbSexo;
    private javax.swing.JComboBox<String> jCbSexo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTxADireccion;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
