/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.HashSet;
import java.util.Set;
import static javafx.scene.paint.Color.color;


/**
 *
 * @author AG
 */
public class JFraMdi extends javax.swing.JFrame {

    /**
     * 
     * 
     * Creates new form JFraMdi
     */
    public JFraMdi() {
        initComponents();
        this.jPlClientes.setVisible(false);
        this.jPlCuenta.setVisible(false);
        this.jPlRegistroTablaCliente.setVisible(false);
        this.jPlCuenta.setVisible(true);
        
       
        
        jTFApellido.setBackground(new Color(0,0,0,0));
        jTFNombre.setBackground(new Color(0,0,0,0));
        jTFId.setBackground(new Color(0,0,0,0));
        jTFTelefono.setBackground(new Color(0,0,0,0));
        jTFBuscarNombre.setBackground(new Color(0,0,0,0));
        jPlRegistroCliente.setBackground(new Color(0,0,0,100));
        jTFIdCuenta.setBackground(new Color(0,0,0,0));
        jTFFecha.setBackground(new Color(0,0,0,0));
        jTFSaldo.setBackground(new Color(0,0,0,0));
       
        
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        scroll.setBorder(null);
        
        
        
        
        jTxADireccion.setBackground(new Color(0,0,0,0));
        
        
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jPlPrincipal = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPlClientes = new javax.swing.JPanel();
        jPlRegistroCliente = new javax.swing.JPanel();
        jPlCuenta = new javax.swing.JPanel();
        jTFIdCuenta = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jTFFecha = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jTFSaldo = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jCbCliente = new javax.swing.JComboBox<>();
        jCbTipoCuenta = new javax.swing.JComboBox<>();
        jTituloCuenta = new javax.swing.JLabel();
        jPlVizualizarCuenta = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jPnlNuevoCuenta = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jPnlGuardarCuenta = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jPnlEditarCuenta = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jPnlEliminarCuenta = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jPnlCancelarCuenta = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLCuenta = new javax.swing.JLabel();
        jPlRegistroTablaCliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jTFBuscarNombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jPlVolverCliente = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPnlEditarCliente = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jCbSexo1 = new javax.swing.JComboBox<>();
        jPnlGuardarCliente = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jTituloCliente = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jPnlNuevoCliente = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jTFApellido = new javax.swing.JTextField();
        jTFId = new javax.swing.JTextField();
        jCbSexo = new javax.swing.JComboBox<>();
        jPnlEliminarCliente = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPnlCancelarCliente = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jTFTelefono = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        jTxADireccion = new javax.swing.JTextArea();
        jPlVizualizarCliente = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPlClienteBoton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPlCuentaBoton = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPlPrincipal.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPlPrincipalComponentAdded(evt);
            }
        });
        jPlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel14.setText("Informacion de estos.");
        jPlPrincipal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel15.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel15.setText("Nuestros Clientes Y sus Respectivas");
        jPlPrincipal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel16.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        jLabel16.setText("Cuentas");
        jPlPrincipal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel18.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel18.setText("Systema pensado para llevar Registro de ");
        jPlPrincipal.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPlPrincipal.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 290, -1));

        jLabel17.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        jLabel17.setText("Bienvenido a Banco Xyz System");
        jPlPrincipal.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel19.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel19.setText("De Clientes.");
        jPlPrincipal.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel20.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel20.setText("De nuestros Clientes para poder tener");
        jPlPrincipal.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));
        jPlPrincipal.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        jPlPrincipal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPlPrincipal.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, -1));

        jLabel22.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        jLabel22.setText("Clientes");
        jPlPrincipal.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel23.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel23.setText("Nos Aseguramos de Tomar los Datos ");
        jPlPrincipal.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel24.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel24.setText("Informacion de Cuentas al dia,");
        jPlPrincipal.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabel25.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel25.setText("Registro y control de cuentas");
        jPlPrincipal.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));
        jPlPrincipal.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 140, -1));
        jPlPrincipal.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja-fuerte.png"))); // NOI18N
        jPlPrincipal.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        jLabel13.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel13.setText("Cuentas bancarias de la mejor manera.");
        jPlPrincipal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banco.png"))); // NOI18N
        jPlPrincipal.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/servicio-al-cliente.png"))); // NOI18N
        jPlPrincipal.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dinero.png"))); // NOI18N
        jPlPrincipal.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        getContentPane().add(jPlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 700, 480));

        jPanel1.setBackground(new java.awt.Color(36, 47, 55));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Banco XYZ System");
        jLabel1.setAutoscrolls(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 700, 40));

        jPlClientes.setBackground(new java.awt.Color(255, 255, 255));
        jPlClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPlRegistroCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPlCuenta.setBackground(new java.awt.Color(255, 255, 255));
        jPlCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFIdCuenta.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFIdCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jTFIdCuenta.setText("Id:");
        jTFIdCuenta.setBorder(null);
        jPlCuenta.add(jTFIdCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 30, -1));
        jPlCuenta.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 190, 10));

        jTFFecha.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFFecha.setForeground(new java.awt.Color(255, 255, 255));
        jTFFecha.setText("Ingresar Fecha");
        jTFFecha.setBorder(null);
        jTFFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFFechaMousePressed(evt);
            }
        });
        jPlCuenta.add(jTFFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, -1));
        jPlCuenta.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 190, 10));

        jTFSaldo.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFSaldo.setForeground(new java.awt.Color(255, 255, 255));
        jTFSaldo.setText("Ingresar Saldo");
        jTFSaldo.setBorder(null);
        jTFSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFSaldoMouseClicked(evt);
            }
        });
        jPlCuenta.add(jTFSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 180, -1));
        jPlCuenta.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 190, 10));

        jCbCliente.setBackground(new java.awt.Color(255, 255, 255));
        jCbCliente.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jCbCliente.setForeground(new java.awt.Color(255, 255, 255));
        jCbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPlCuenta.add(jCbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 190, -1));

        jCbTipoCuenta.setBackground(new java.awt.Color(255, 255, 255));
        jCbTipoCuenta.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jCbTipoCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jCbTipoCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPlCuenta.add(jCbTipoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 190, -1));

        jTituloCuenta.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        jTituloCuenta.setText("Area Cuenta");
        jPlCuenta.add(jTituloCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jPlVizualizarCuenta.setBackground(new java.awt.Color(255, 102, 0));
        jPlVizualizarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPlVizualizarCuentaMouseClicked(evt);
            }
        });
        jPlVizualizarCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("  ↓ Vizualizar");
        jPlVizualizarCuenta.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jPlCuenta.add(jPlVizualizarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 130, 20));

        jPnlNuevoCuenta.setBackground(new java.awt.Color(36, 47, 70));
        jPnlNuevoCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlNuevoCuentaMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPnlNuevoCuentaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPnlNuevoCuentaMouseEntered(evt);
            }
        });

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Nuevo");
        jPnlNuevoCuenta.add(jLabel46);

        jPlCuenta.add(jPnlNuevoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 130, 30));

        jPnlGuardarCuenta.setBackground(new java.awt.Color(36, 47, 70));
        jPnlGuardarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlGuardarCuentaMousePressed(evt);
            }
        });

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Guardar");
        jPnlGuardarCuenta.add(jLabel47);

        jPlCuenta.add(jPnlGuardarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 130, 30));

        jPnlEditarCuenta.setBackground(new java.awt.Color(36, 47, 70));
        jPnlEditarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlEditarCuentaMousePressed(evt);
            }
        });

        jLabel48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel48.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Editar");
        jPnlEditarCuenta.add(jLabel48);

        jPlCuenta.add(jPnlEditarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 218, 130, 30));

        jPnlEliminarCuenta.setBackground(new java.awt.Color(36, 47, 70));
        jPnlEliminarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlEliminarCuentaMousePressed(evt);
            }
        });

        jLabel49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel49.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Eliminar");
        jPnlEliminarCuenta.add(jLabel49);

        jPlCuenta.add(jPnlEliminarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 130, 30));

        jPnlCancelarCuenta.setBackground(new java.awt.Color(36, 47, 70));
        jPnlCancelarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlCancelarCuentaMousePressed(evt);
            }
        });

        jLabel50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel50.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Cancelar");
        jPnlCancelarCuenta.add(jLabel50);

        jPlCuenta.add(jPnlCancelarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 130, 30));

        jLCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/37976146_1807186072706267_8377348829132881920_n.png"))); // NOI18N
        jLCuenta.setText("jLabel44");
        jPlCuenta.add(jLCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        jPlRegistroCliente.add(jPlCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        jPlRegistroTablaCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPlRegistroTablaCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPlRegistroTablaCliente.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 95, 550, 260));
        jPlRegistroTablaCliente.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 360, -1));

        jTFBuscarNombre.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jTFBuscarNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTFBuscarNombre.setText("Buscar Cliente");
        jTFBuscarNombre.setBorder(null);
        jTFBuscarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFBuscarNombreMousePressed(evt);
            }
        });
        jPlRegistroTablaCliente.add(jTFBuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 360, -1));
        jPlRegistroTablaCliente.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -10, -1, -1));
        jPlRegistroTablaCliente.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, -1));
        jPlRegistroTablaCliente.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, -1, -1));

        jPlRegistroCliente.add(jPlRegistroTablaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 660, 400));

        jLabel42.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Registro Clientes");
        jPlRegistroCliente.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jPlVolverCliente.setBackground(new java.awt.Color(0, 153, 51));
        jPlVolverCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPlVolverClienteMouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("← Volver");
        jPlVolverCliente.add(jLabel34);

        jPlRegistroCliente.add(jPlVolverCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 120, 30));

        jPlClientes.add(jPlRegistroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        jPnlEditarCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlEditarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlEditarClienteMousePressed(evt);
            }
        });

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Editar");
        jPnlEditarCliente.add(jLabel37);

        jPlClientes.add(jPnlEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 218, 130, 30));

        jCbSexo1.setBackground(new java.awt.Color(255, 255, 255));
        jCbSexo1.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jCbSexo1.setForeground(new java.awt.Color(255, 255, 255));
        jCbSexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPlClientes.add(jCbSexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, -1));

        jPnlGuardarCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlGuardarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlGuardarClienteMousePressed(evt);
            }
        });

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Guardar");
        jPnlGuardarCliente.add(jLabel36);

        jPlClientes.add(jPnlGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 130, 30));
        jPlClientes.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 190, 10));

        jTituloCliente.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        jTituloCliente.setText("Area Clientes");
        jPlClientes.add(jTituloCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jTFNombre.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTFNombre.setText("Ingresar Nombre");
        jTFNombre.setBorder(null);
        jTFNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFNombreMousePressed(evt);
            }
        });
        jPlClientes.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, -1));
        jPlClientes.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 190, 10));
        jPlClientes.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 190, 10));
        jPlClientes.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 190, 10));

        jPnlNuevoCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlNuevoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlNuevoClienteMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPnlNuevoClienteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPnlNuevoClienteMouseEntered(evt);
            }
        });

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Nuevo");
        jPnlNuevoCliente.add(jLabel35);

        jPlClientes.add(jPnlNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 130, 30));

        jTFApellido.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFApellido.setForeground(new java.awt.Color(255, 255, 255));
        jTFApellido.setText("Ingresar Apellido");
        jTFApellido.setBorder(null);
        jTFApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFApellidoMousePressed(evt);
            }
        });
        jPlClientes.add(jTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 180, -1));

        jTFId.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFId.setForeground(new java.awt.Color(255, 255, 255));
        jTFId.setText("Id:");
        jTFId.setBorder(null);
        jTFId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFIdMousePressed(evt);
            }
        });
        jPlClientes.add(jTFId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 30, -1));

        jCbSexo.setBackground(new java.awt.Color(255, 255, 255));
        jCbSexo.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jCbSexo.setForeground(new java.awt.Color(255, 255, 255));
        jCbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPlClientes.add(jCbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 190, -1));

        jPnlEliminarCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlEliminarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlEliminarClienteMousePressed(evt);
            }
        });

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Eliminar");
        jPnlEliminarCliente.add(jLabel38);

        jPlClientes.add(jPnlEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 130, 30));

        jPnlCancelarCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlCancelarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlCancelarClienteMousePressed(evt);
            }
        });

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Cancelar");
        jPnlCancelarCliente.add(jLabel39);

        jPlClientes.add(jPnlCancelarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 130, 30));

        jTFTelefono.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jTFTelefono.setText("Ingresar Telefono");
        jTFTelefono.setBorder(null);
        jTFTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFTelefonoMousePressed(evt);
            }
        });
        jPlClientes.add(jTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 180, -1));

        jTxADireccion.setColumns(20);
        jTxADireccion.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTxADireccion.setForeground(new java.awt.Color(255, 255, 255));
        jTxADireccion.setRows(5);
        jTxADireccion.setText("Direccion");
        jTxADireccion.setToolTipText("");
        jTxADireccion.setOpaque(false);
        jTxADireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTxADireccionMousePressed(evt);
            }
        });
        scroll.setViewportView(jTxADireccion);

        jPlClientes.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 320, 100));

        jPlVizualizarCliente.setBackground(new java.awt.Color(255, 102, 0));
        jPlVizualizarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPlVizualizarClienteMouseClicked(evt);
            }
        });
        jPlVizualizarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("  ↓ Vizualizar");
        jPlVizualizarCliente.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jPlClientes.add(jPlVizualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 130, 20));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clientes.png"))); // NOI18N
        jPlClientes.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        getContentPane().add(jPlClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 700, 480));

        jPanel2.setBackground(new java.awt.Color(36, 47, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAlignmentX(0.1F);
        jSeparator1.setAlignmentY(0.1F);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 140, -1));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setAlignmentX(0.3F);
        jSeparator2.setAlignmentY(0.3F);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, -1));

        jLabel4.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Fecha:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, 20));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menú");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 20));

        jLabel6.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 51));
        jLabel6.setText("Usuario Activo:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jPlClienteBoton.setBackground(new java.awt.Color(36, 47, 70));
        jPlClienteBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPlClienteBotonMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPlClienteBotonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPlClienteBotonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPlClienteBotonMouseEntered(evt);
            }
        });
        jPlClienteBoton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Clientes");
        jPlClienteBoton.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 24));
        jPlClienteBoton.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(jPlClienteBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 40));

        jPlCuentaBoton.setBackground(new java.awt.Color(36, 47, 70));
        jPlCuentaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPlCuentaBotonMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPlCuentaBotonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPlCuentaBotonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPlCuentaBotonMouseEntered(evt);
            }
        });
        jPlCuentaBoton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cuenta");
        jPlCuentaBoton.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));
        jPlCuentaBoton.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(jPlCuentaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 40));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bank-flat/64x64.png"))); // NOI18N
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPlCuentaBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlCuentaBotonMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPlCuentaBotonMouseEntered

    private void jPlCuentaBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlCuentaBotonMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jPlCuentaBotonMouseExited

    private void jPlCuentaBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlCuentaBotonMousePressed
        // TODO add your handling code here:
        jPlCuentaBoton.setBackground(new Color(0,153,51));
        jPlClienteBoton.setBackground(new Color(36,47,70));
    }//GEN-LAST:event_jPlCuentaBotonMousePressed

    private void jPlClienteBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlClienteBotonMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPlClienteBotonMouseEntered

    private void jPlClienteBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlClienteBotonMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jPlClienteBotonMouseExited

    private void jPlClienteBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlClienteBotonMousePressed
        // TODO add your handling code here
        jPlClienteBoton.setBackground(new Color(0,153,51));
        jPlCuentaBoton.setBackground(new Color(36,47,70));
    }//GEN-LAST:event_jPlClienteBotonMousePressed

    private void jTFApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFApellidoMousePressed
        // TODO add your handling code here:
        jTFApellido.setText("");
    }//GEN-LAST:event_jTFApellidoMousePressed

    private void jTFNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNombreMousePressed
        // TODO add your handling code here:
        jTFNombre.setText("");
    }//GEN-LAST:event_jTFNombreMousePressed

    private void jTFIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFIdMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIdMousePressed

    private void jTFTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFTelefonoMousePressed
        // TODO add your handling code here:
        jTFTelefono.setText("");
    }//GEN-LAST:event_jTFTelefonoMousePressed

    private void jTxADireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxADireccionMousePressed
        // TODO add your handling code here:
        jTxADireccion.setText("");
    }//GEN-LAST:event_jTxADireccionMousePressed

    private void jPnlNuevoClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlNuevoClienteMousePressed
        // TODO add your handling code here:
        jPnlNuevoCliente.setBackground(new Color(0,153,51));
        jPnlGuardarCliente.setBackground(new Color(36,47,70));
        jPnlEditarCliente.setBackground(new Color(36,47,70));
        jPnlEliminarCliente.setBackground(new Color(36,47,70));
        jPnlCancelarCliente.setBackground(new Color(36,47,70));

    }//GEN-LAST:event_jPnlNuevoClienteMousePressed

    private void jPnlNuevoClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlNuevoClienteMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jPnlNuevoClienteMouseExited

    private void jPnlNuevoClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlNuevoClienteMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPnlNuevoClienteMouseEntered

    private void jPnlGuardarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlGuardarClienteMousePressed
        // TODO add your handling code here:
        jPnlGuardarCliente.setBackground(new Color(0,153,51));
        jPnlNuevoCliente.setBackground(new Color(36,47,70));
        jPnlEditarCliente.setBackground(new Color(36,47,70));
        jPnlEliminarCliente.setBackground(new Color(36,47,70));
        jPnlCancelarCliente.setBackground(new Color(36,47,70));

    }//GEN-LAST:event_jPnlGuardarClienteMousePressed

    private void jPnlEditarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlEditarClienteMousePressed
        // TODO add your handling code here:
        jPnlEditarCliente.setBackground(new Color(0,153,51));
        jPnlGuardarCliente.setBackground(new Color(36,47,70));
        jPnlNuevoCliente.setBackground(new Color(36,47,70));
        jPnlEliminarCliente.setBackground(new Color(36,47,70));
        jPnlCancelarCliente.setBackground(new Color(36,47,70));

    }//GEN-LAST:event_jPnlEditarClienteMousePressed

    private void jPnlEliminarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlEliminarClienteMousePressed
        // TODO add your handling code here:
        jPnlEliminarCliente.setBackground(new Color(0,153,51));
        jPnlGuardarCliente.setBackground(new Color(36,47,70));
        jPnlNuevoCliente.setBackground(new Color(36,47,70));
        jPnlEditarCliente.setBackground(new Color(36,47,70));
        jPnlCancelarCliente.setBackground(new Color(36,47,70));

    }//GEN-LAST:event_jPnlEliminarClienteMousePressed

    private void jPnlCancelarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlCancelarClienteMousePressed
        // TODO add your handling code here:
        jPnlCancelarCliente.setBackground(new Color(0,153,51));
        jPnlGuardarCliente.setBackground(new Color(36,47,70));
        jPnlNuevoCliente.setBackground(new Color(36,47,70));
        jPnlEditarCliente.setBackground(new Color(36,47,70));
        jPnlEliminarCliente.setBackground(new Color(36,47,70));

    }//GEN-LAST:event_jPnlCancelarClienteMousePressed

    private void jPlPrincipalComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPlPrincipalComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlPrincipalComponentAdded

    private void jPlClienteBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlClienteBotonMouseClicked
        // TODO add your handling code here:
        this.jPlClientes.setVisible(true);
        this.jPlPrincipal.setVisible(false);
        this.jPlCuenta.setVisible(false);
        jPlRegistroCliente.setVisible(false);
        jTFApellido.setVisible(true);
        jTFId.setVisible(true);
        jTFNombre.setVisible(true);
        jTFTelefono.setVisible(true);
        jTFApellido.setEnabled(true);
        jTFId.setEnabled(true);
        jTFTelefono.setEnabled(true);
        jPlRegistroCliente.setVisible(false);
        jTFNombre.setEnabled(true);
        jTituloCliente.setVisible(true);
        jPnlNuevoCliente.setVisible(true);
        jPnlGuardarCliente.setVisible(true);
        jPnlEditarCliente.setVisible(true);
        jPnlEliminarCliente.setVisible(true);
        jPnlCancelarCliente.setVisible(true);
        jPnlNuevoCliente.setEnabled(true);
        jPnlGuardarCliente.setEnabled(true);
        jPnlEditarCliente.setEnabled(true);
        jPnlEliminarCliente.setEnabled(true);
        jPnlCancelarCliente.setEnabled(true);
        jCbSexo.setVisible(true);
        jCbSexo.setEnabled(true);
        jCbSexo1.setVisible(true);
        jCbSexo1.setEnabled(true);
        jTxADireccion.setVisible(true);
        jTxADireccion.setEnabled(true);
        jPlVizualizarCliente.setEnabled(true);
        jPlVizualizarCliente.setVisible(true);
        
       
        
    }//GEN-LAST:event_jPlClienteBotonMouseClicked

    private void jPlVizualizarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlVizualizarClienteMouseClicked
        // TODO add your handling code here:
         this.jPlCuenta.setVisible(false);
         this.jLCuenta.setVisible(false);
         jTFApellido.setVisible(false);
         jTFId.setVisible(false);
         jTFNombre.setVisible(false);
         jTFTelefono.setVisible(false);
         jTFApellido.setEnabled(false);
         jTFId.setEnabled(false);
         jTFTelefono.setEnabled(false);
         jPlRegistroCliente.setVisible(true);
         jTFNombre.setEnabled(false);
         jTituloCliente.setVisible(false);
         jPnlNuevoCliente.setVisible(false);
         jPnlGuardarCliente.setVisible(false);
         jPnlEditarCliente.setVisible(false);
         jPnlEliminarCliente.setVisible(false);
         jPnlCancelarCliente.setVisible(false);
         jPnlNuevoCliente.setEnabled(false);
         jPnlGuardarCliente.setEnabled(false);
         jPnlEditarCliente.setEnabled(false);
         jPnlEliminarCliente.setEnabled(false);
         jPnlCancelarCliente.setEnabled(false);
         jCbSexo.setVisible(false);
         jCbSexo.setEnabled(false);
         jCbSexo1.setVisible(false);
         jCbSexo1.setEnabled(false);
         jTxADireccion.setVisible(false);
         jTxADireccion.setEnabled(false);
         jPlVizualizarCliente.setEnabled(false);
         jPlVizualizarCliente.setVisible(false);
         this.jPlRegistroTablaCliente.setVisible(true);
         
         
        
        
    }//GEN-LAST:event_jPlVizualizarClienteMouseClicked

    private void jTFBuscarNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFBuscarNombreMousePressed
        // TODO add your handling code here:
        jTFBuscarNombre.setText("");
    }//GEN-LAST:event_jTFBuscarNombreMousePressed

    private void jPlVolverClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlVolverClienteMouseClicked
        // TODO add your handling code here:
        this.jPlClientes.setVisible(true);
        this.jPlPrincipal.setVisible(false);
        jPlRegistroCliente.setVisible(false);
        jTFApellido.setVisible(true);
         jTFId.setVisible(true);
         jTFNombre.setVisible(true);
         jTFTelefono.setVisible(true);
         jTFApellido.setEnabled(true);
         jTFId.setEnabled(true);
         jTFTelefono.setEnabled(true);
         jPlRegistroCliente.setVisible(false);
         jTFNombre.setEnabled(true);
         jTituloCliente.setVisible(true);
         jPnlNuevoCliente.setVisible(true);
         jPnlGuardarCliente.setVisible(true);
         jPnlEditarCliente.setVisible(true);
         jPnlEliminarCliente.setVisible(true);
         jPnlCancelarCliente.setVisible(true);
         jPnlNuevoCliente.setEnabled(true);
         jPnlGuardarCliente.setEnabled(true);
         jPnlEditarCliente.setEnabled(true);
         jPnlEliminarCliente.setEnabled(true);
         jPnlCancelarCliente.setEnabled(true);
         jCbSexo.setVisible(true);
         jCbSexo.setEnabled(true);
         jCbSexo1.setVisible(true);
         jCbSexo1.setEnabled(true);
         jTxADireccion.setVisible(true);
         jTxADireccion.setEnabled(true);
         jPlVizualizarCliente.setEnabled(true);
         jPlVizualizarCliente.setVisible(true);
         jTFBuscarNombre.setText("Buscar Cliente");
    }//GEN-LAST:event_jPlVolverClienteMouseClicked

    private void jTFFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFFechaMousePressed
        // TODO add your handling code here:
        jTFFecha.setText("");
    }//GEN-LAST:event_jTFFechaMousePressed

    private void jTFSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFSaldoMouseClicked
        // TODO add your handling code here:
        jTFSaldo.setText("");
    }//GEN-LAST:event_jTFSaldoMouseClicked

    private void jPlVizualizarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlVizualizarCuentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlVizualizarCuentaMouseClicked

    private void jPnlNuevoCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlNuevoCuentaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPnlNuevoCuentaMousePressed

    private void jPnlNuevoCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlNuevoCuentaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPnlNuevoCuentaMouseExited

    private void jPnlNuevoCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlNuevoCuentaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPnlNuevoCuentaMouseEntered

    private void jPnlGuardarCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlGuardarCuentaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPnlGuardarCuentaMousePressed

    private void jPnlEditarCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlEditarCuentaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPnlEditarCuentaMousePressed

    private void jPnlEliminarCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlEliminarCuentaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPnlEliminarCuentaMousePressed

    private void jPnlCancelarCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlCancelarCuentaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPnlCancelarCuentaMousePressed

    private void jPlCuentaBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlCuentaBotonMouseClicked
        // TODO add your handling code here:
        this.jPlCuenta.setVisible(true);
        this.jPlClientes.setVisible(false);
        this.jPlPrincipal.setVisible(false);
        this.jPlRegistroCliente.setVisible(false);
        jPlRegistroCliente.setVisible(false);
        jTFFecha.setVisible(true);
        jTFFecha.setEnabled(true);
        jTFIdCuenta.setVisible(true);
        jTFIdCuenta.setEnabled(true);
        jTFSaldo.setVisible(true);
        jTFSaldo.setEnabled(true);
        jCbCliente.setVisible(true);
        jCbCliente.setEnabled(true);
        jCbTipoCuenta.setVisible(true);
        jCbTipoCuenta.setEnabled(true);
        jPnlNuevoCuenta.setVisible(true);
        jPnlGuardarCuenta.setVisible(true);
        jPnlEditarCuenta.setVisible(true);
        jPnlEliminarCuenta.setVisible(true);
        jPnlCancelarCuenta.setVisible(true);
        this.jLCuenta.setVisible(true);
        
       
        
        
        
        
        
        
        
    }//GEN-LAST:event_jPlCuentaBotonMouseClicked

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFraMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFraMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFraMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFraMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFraMdi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCbCliente;
    private javax.swing.JComboBox<String> jCbSexo;
    private javax.swing.JComboBox<String> jCbSexo1;
    private javax.swing.JComboBox<String> jCbTipoCuenta;
    private javax.swing.JLabel jLCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPlClienteBoton;
    private javax.swing.JPanel jPlClientes;
    private javax.swing.JPanel jPlCuenta;
    private javax.swing.JPanel jPlCuentaBoton;
    private javax.swing.JPanel jPlPrincipal;
    private javax.swing.JPanel jPlRegistroCliente;
    private javax.swing.JPanel jPlRegistroTablaCliente;
    private javax.swing.JPanel jPlVizualizarCliente;
    private javax.swing.JPanel jPlVizualizarCuenta;
    private javax.swing.JPanel jPlVolverCliente;
    private javax.swing.JPanel jPnlCancelarCliente;
    private javax.swing.JPanel jPnlCancelarCuenta;
    private javax.swing.JPanel jPnlEditarCliente;
    private javax.swing.JPanel jPnlEditarCuenta;
    private javax.swing.JPanel jPnlEliminarCliente;
    private javax.swing.JPanel jPnlEliminarCuenta;
    private javax.swing.JPanel jPnlGuardarCliente;
    private javax.swing.JPanel jPnlGuardarCuenta;
    private javax.swing.JPanel jPnlNuevoCliente;
    private javax.swing.JPanel jPnlNuevoCuenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFBuscarNombre;
    private javax.swing.JTextField jTFFecha;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFIdCuenta;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFSaldo;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jTituloCliente;
    private javax.swing.JLabel jTituloCuenta;
    private javax.swing.JTextArea jTxADireccion;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables

    private static class jBtnClientes {

        private static void setBackground(Color color) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public jBtnClientes() {
        }
    }
}
